/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export type JsRoaringBitmap = RoaringBitmap
export declare class RoaringBitmap {
  constructor()
  insert(value: number): void
  remove(value: number): void
  isDisjoint(other: RoaringBitmap): boolean
  isSubset(other: RoaringBitmap): boolean
  isSuperset(other: RoaringBitmap): boolean
  static full(): RoaringBitmap
  container(value: number): boolean
  clear(): void
  get length(): number
}
